//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelFileUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer1
    {
        public int sr { get; set; }
        public string CompanyName { get; set; }
        public string GSTIN { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string TurnoveAmount { get; set; }
        public string ContactEmail { get; set; }
        public string ContactNumber { get; set; }
    }
}
